-- Fix coordinates precision
-- Change from DECIMAL(10, 7) to DOUBLE PRECISION for better GPS accuracy

ALTER TABLE reports
  ALTER COLUMN lat TYPE DOUBLE PRECISION,
  ALTER COLUMN lng TYPE DOUBLE PRECISION;

ALTER TABLE partner_stores
  ALTER COLUMN lat TYPE DOUBLE PRECISION,
  ALTER COLUMN lng TYPE DOUBLE PRECISION;
